### ISSUE TITLE
Improve impl. when neither -b nor -t is specified

### ISSUE THREAD

**Issue by YouQam** [o2r-project/geoextent#44]

**Comment by YouQam** [comment]
Recent impl. raises the following exception:  
```
       if bbox == False and tbox == False:
        raise Exception("Please enter correct arguments")
```

**Comment by nuest** [comment]
```
(geoextent) daniel@nuest ~/git/o2r/geoextent [master]$ geoextent README.md 
ERROR:geoextent:Require at least one of extraction options, but bbox is False and tbox is False
ERROR:geoextent:No extraction options enabled!
Traceback (most recent call last):
  File "/home/daniel/git/o2r/geoextent/geoextent/__main__.py", line 149, in main
    output = extent.fromFile(files, bbox = args['bounding_box'], tbox = args['time_box'])
  File "/home/daniel/git/o2r/geoextent/geoextent/lib/extent.py", line 57, in fromFile
    raise Exception("No extraction options enabled!")
Exception: No extraction options enabled!
```
